//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Propeus.Modulo.Dinamico.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Propeus.Modulo.Dinamico.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dinamico.Diretorio.Modulos.
        /// </summary>
        internal static string DinamicoDiretorioModulos {
            get {
                return ResourceManager.GetString("DinamicoDiretorioModulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dinamico.Modulos.AutoInicializados.
        /// </summary>
        internal static string DinamicoDiretorioModulosAutoInicializados {
            get {
                return ResourceManager.GetString("DinamicoDiretorioModulosAutoInicializados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dinamico.Modulos.Ignorados.
        /// </summary>
        internal static string DinamicoDiretorioModulosIgnorados {
            get {
                return ResourceManager.GetString("DinamicoDiretorioModulosIgnorados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dinamico.Modulos.Validos.
        /// </summary>
        internal static string DinamicoDiretorioModulosValidos {
            get {
                return ResourceManager.GetString("DinamicoDiretorioModulosValidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dinamico.Intervalo.Atualizacao.
        /// </summary>
        internal static string DinamicoIntervaloAtualizacaoModulo {
            get {
                return ResourceManager.GetString("DinamicoIntervaloAtualizacaoModulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ambiguidade de nome: {0}.
        /// </summary>
        internal static string ERRO_AMBIGUIDADE_NOME {
            get {
                return ResourceManager.GetString("ERRO_AMBIGUIDADE_NOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O gerenciador &apos;{0}&apos; não possui a interface &apos;{1}&apos;.
        /// </summary>
        internal static string ERRO_GERENCIADOR_NAO_POSSUI_INTERFACE {
            get {
                return ResourceManager.GetString("ERRO_GERENCIADOR_NAO_POSSUI_INTERFACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} não encontrado.
        /// </summary>
        internal static string ERRO_ID_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("ERRO_ID_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} nulo ou vazio.
        /// </summary>
        internal static string ERRO_ID_NULO_OU_VAZIO {
            get {
                return ResourceManager.GetString("ERRO_ID_NULO_OU_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nao foi possivel encontrar o modulo &apos;{0}&apos;, verifique se o nome foi digitado corretamente ou se o mesmo foi carregado..
        /// </summary>
        internal static string ERRO_MODULO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("ERRO_MODULO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O tipo não é um modulo valido.
        /// </summary>
        internal static string ERRO_TIPO_MODULO_INVALIDO {
            get {
                return ResourceManager.GetString("ERRO_TIPO_MODULO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a *.dll.
        /// </summary>
        internal static string EXT_DLL {
            get {
                return ResourceManager.GetString("EXT_DLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .index.
        /// </summary>
        internal static string EXT_INDICE {
            get {
                return ResourceManager.GetString("EXT_INDICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Criando indice..
        /// </summary>
        internal static string INFO_INDICE_CRIADO {
            get {
                return ResourceManager.GetString("INFO_INDICE_CRIADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lendo indice..
        /// </summary>
        internal static string INFO_INDICE_LIDO {
            get {
                return ResourceManager.GetString("INFO_INDICE_LIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um mapeamento de modulos em andamento..
        /// </summary>
        internal static string INFO_MAPEAMENTO_EM_ANDAMENTO {
            get {
                return ResourceManager.GetString("INFO_MAPEAMENTO_EM_ANDAMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Modulo &apos;{0}&apos; mapeado..
        /// </summary>
        internal static string INFO_MODULO_MAPEADO {
            get {
                return ResourceManager.GetString("INFO_MODULO_MAPEADO", resourceCulture);
            }
        }
    }
}
