trigger:
- master
- dev

resources:
  repositories:
    - repository: templates
      type: git
      name: Propeus.Modulo/Propeus.Modulo.Templates

jobs:
- template: Build-template.yml@templates
  parameters:
    vmImage: 'windows-2019'
    name: 'windows_2019'
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
    versaoSDK: '3.1.100'
    nomeArtefato: 'artefato'

- template: Build-template.yml@templates
  parameters:
    vmImage: 'vs2017-win2016'
    name: 'vs2017_win2016'
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
    versaoSDK: '3.1.100'
    nomeArtefato: 'artefato'

- template: Build-template.yml@templates
  parameters:
    vmImage: 'macOS-10.14'
    name: 'macOS_10_14'
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
    versaoSDK: '3.1.100'
    nomeArtefato: 'artefato'

- template: Build-template.yml@templates
  parameters:
    vmImage: 'ubuntu-16.04'
    name: 'ubuntu_16_04'
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
    versaoSDK: '3.1.100'
    nomeArtefato: 'artefato'