//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Propeus.Modulo.Util.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Propeus.Modulo.Util.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O argumento não é do tipo {0}.
        /// </summary>
        public static string ARGUMENTO_NAO_E_DO_TIPO {
            get {
                return ResourceManager.GetString("ARGUMENTO_NAO_E_DO_TIPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O argumento não pode ser do tipo {0}.
        /// </summary>
        public static string ARGUMENTO_NAO_PODE_SER_DO_TIPO {
            get {
                return ResourceManager.GetString("ARGUMENTO_NAO_PODE_SER_DO_TIPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O argumento não pode ser nulo.
        /// </summary>
        public static string ARGUMENTO_NULO {
            get {
                return ResourceManager.GetString("ARGUMENTO_NULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O argumento não pode ser nulo ou vazio.
        /// </summary>
        public static string ARGUMENTO_NULO_OU_VAZIO {
            get {
                return ResourceManager.GetString("ARGUMENTO_NULO_OU_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível encontrar o atributo {0} no objeto {1}.
        /// </summary>
        public static string ATRIBUTO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("ATRIBUTO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a W83sjKUHmkA!@d6Vgyrk=T^Nk^d2VD?Tasr?cAdHE#JE%Xr4Sg-KM9zTkF_v?nEm!_GcmjhYf7ajKS=?zfe5zKMaK%ej9k4JvUKsBA$L=JyEAK%xY@hfX@PKyG!jcDY7R3c-B+9rJ75x6Tpya!^FkbB3_eQ%fmY@Rdqdb#wk$w$wM*wuFwpwfK=4pz&amp;$hj&amp;C!EWGWE!UTCEux-Sdm?Hy6CSb9f$3EEW+@*BCA$D4Y_rptJ4-P#44Ztg#pQX!CSnn^YNcyYjWZV#6Uaw4cbL#zGDEay7ZJgy-NfZS@j^z#GGXfHgTJ&amp;U9KYnEz?Spr_xC6=_-Q*@MbNqE5%sjmbXqB3v9GA-Y95u8rHXkYCjp_L46FFwq-aRB4wK6z?v#FVsdWxqt%gTr_kbVFwEnguWktyXd^#=QjD!vQ++Z-#YX?3Gug4?mPC87u=ee_WqmQ9v7Q?Jz##q%+Zv^Xq&amp;gCjQ9mZvkh&amp;gvN@!JNgrraZbPsv58bYC?ySbUqEp4q5mf$jFg [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string DATA_HASH_KEY {
            get {
                return ResourceManager.GetString("DATA_HASH_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Enum não possui uma descrição..
        /// </summary>
        public static string ENUM_SEM_DESCRICAO {
            get {
                return ResourceManager.GetString("ENUM_SEM_DESCRICAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O método será removido nas próximas versões..
        /// </summary>
        public static string OBSOLETO_REMOCAO {
            get {
                return ResourceManager.GetString("OBSOLETO_REMOCAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível obter atributos de um tipo herdado de Attribute.
        /// </summary>
        public static string PARAMETRO_ATRIBUTO_INVALIDO {
            get {
                return ResourceManager.GetString("PARAMETRO_ATRIBUTO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível converter o parâmetro &apos;{0}&apos; para &apos;{1}&apos;..
        /// </summary>
        public static string PARAMETRO_NAO_CONVERTIDO {
            get {
                return ResourceManager.GetString("PARAMETRO_NAO_CONVERTIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível encontrar o arquivo do programa atual.
        /// </summary>
        public static string PROGRAMA_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("PROGRAMA_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível converter o tipo &apos;{0}&apos; para {1}..
        /// </summary>
        public static string TIPO_NAO_CONVERTIDO {
            get {
                return ResourceManager.GetString("TIPO_NAO_CONVERTIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível encontrar o valor padrão do parâmetro &apos;{0}&apos;..
        /// </summary>
        public static string VALOR_PADRAO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("VALOR_PADRAO_NAO_ENCONTRADO", resourceCulture);
            }
        }
    }
}
