trigger:
- master
- develop
- feature/*
- hotfix/*

resources:
  repositories:
    - repository: templates
      type: git
      name: Propeus.Modulo/Propeus.Modulo.Templates

jobs:
- template: Build-template.yml@templates
  parameters:
    vmImage: 'windows-2019'
    name: 'windows_2019'
    solution: '**/*.sln'
    nuget: '*.nupkg'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
    pathCoverage: '$(Build.SourcesDirectory)\TestResults\Coverage\coverage.opencover.xml'
    versaoSDK: '5.0.x'
    nomeArtefato: 'artefato'
    sufixo: ''

- template: Build-template.yml@templates
  parameters:
    vmImage: 'vs2017-win2016'
    name: 'vs2017_win2016'
    solution: '**/*.sln'
    nuget: '*.nupkg'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
    pathCoverage: '$(Build.SourcesDirectory)\TestResults\Coverage\coverage.opencover.xml'
    versaoSDK: '5.0.x'
    nomeArtefato: 'artefato'
    sufixo: ''

- template: Build-template.yml@templates
  parameters:
    vmImage: 'macOS-10.14'
    name: 'macOS_10_14'
    solution: '**/*.sln'
    nuget: '*.nupkg'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
    pathCoverage: '$(Build.SourcesDirectory)\TestResults\Coverage\coverage.opencover.xml'
    versaoSDK: '5.0.x'
    nomeArtefato: 'artefato'
    sufixo: ''

- template: Build-template.yml@templates
  parameters:
    vmImage: 'ubuntu-16.04'
    name: 'ubuntu_16_04'
    solution: '**/*.sln'
    nuget: '*.nupkg'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
    pathCoverage: '$(Build.SourcesDirectory)\TestResults\Coverage\coverage.opencover.xml'
    versaoSDK: '5.0.x'
    nomeArtefato: 'artefato'
    sufixo: ''