//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Propeus.Modulo.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Propeus.Modulo.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O parametro &apos;{0}&apos; é nulo ou vazio.
        /// </summary>
        internal static string ERRO_ARGUMENTO_NULO_OU_VAZIO {
            get {
                return ResourceManager.GetString("ERRO_ARGUMENTO_NULO_OU_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O argumento &apos;{0}&apos; requer o tipo &apos;{1}&apos;, o tipo passado foi &apos;{2}&apos;.
        /// </summary>
        internal static string ERRO_ARGUMENTO_TIPO_ESPERADO {
            get {
                return ResourceManager.GetString("ERRO_ARGUMENTO_TIPO_ESPERADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O modulo requer um contrutor com o parametro do tipo IGerenciador.
        /// </summary>
        internal static string ERRO_CONSTRUTOR_IGERENCIADOR_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("ERRO_CONSTRUTOR_IGERENCIADOR_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possivel encontrar um construtor.
        /// </summary>
        internal static string ERRO_CONSTRUTOR_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("ERRO_CONSTRUTOR_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possivel encontrar um construtor com {0} parametros.\nO contrutor {1} requer {2} parametros.
        /// </summary>
        internal static string ERRO_CONSTRUTOR_NAO_ENCONTRADO_PARAMETROS {
            get {
                return ResourceManager.GetString("ERRO_CONSTRUTOR_NAO_ENCONTRADO_PARAMETROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi encontrado o contrutor padrão {0}({1} gerenciador){{2}}.
        /// </summary>
        internal static string ERRO_CONSTRUTOR_PADRAO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("ERRO_CONSTRUTOR_PADRAO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O gerenciador já foi desaativado.
        /// </summary>
        internal static string ERRO_GERENCIADOR_DESATIVADO {
            get {
                return ResourceManager.GetString("ERRO_GERENCIADOR_DESATIVADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possivel encontrar o atributo de contrato.
        /// </summary>
        internal static string ERRO_MODULO_CONTRATO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("ERRO_MODULO_CONTRATO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Modulo &apos;{0}&apos; foi descartado..
        /// </summary>
        internal static string ERRO_MODULO_ID_DESCARTADO {
            get {
                return ResourceManager.GetString("ERRO_MODULO_ID_DESCARTADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não existe modulo do id &apos;{0}&apos;.
        /// </summary>
        internal static string ERRO_MODULO_ID_NAO_ENCONTRAADO {
            get {
                return ResourceManager.GetString("ERRO_MODULO_ID_NAO_ENCONTRAADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possivel criar uma nova instancia de um modulo de instancia unica.
        /// </summary>
        internal static string ERRO_MODULO_INSTANCIA_UNICA {
            get {
                return ResourceManager.GetString("ERRO_MODULO_INSTANCIA_UNICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Modulo &apos;{0}&apos; não encontrado.\nVerifique se o nome esta correto na interface de contrato.
        /// </summary>
        internal static string ERRO_MODULO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("ERRO_MODULO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possivel reiniciar modulos criados fora do gerenciador.
        /// </summary>
        internal static string ERRO_MODULO_NEW_REINICIAR {
            get {
                return ResourceManager.GetString("ERRO_MODULO_NEW_REINICIAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O modulo &apos;{0}::{1}&apos; já foi registrado.
        /// </summary>
        internal static string ERRO_MODULO_REGISTRADO {
            get {
                return ResourceManager.GetString("ERRO_MODULO_REGISTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O modulo &apos;{0}::{1}&apos; já foi registrado no cache..
        /// </summary>
        internal static string ERRO_MODULO_REGISTRADO_CACHE {
            get {
                return ResourceManager.GetString("ERRO_MODULO_REGISTRADO_CACHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Modulo &apos;{0}&apos; não encontrado.
        /// </summary>
        internal static string ERRO_NOME_MODULO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("ERRO_NOME_MODULO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Foi encontrado mais de um tipo do modulo &apos;{0}&apos;..
        /// </summary>
        internal static string ERRO_TIPO_AMBIGUO {
            get {
                return ResourceManager.GetString("ERRO_TIPO_AMBIGUO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O tipo deve ser uma classe ou interface..
        /// </summary>
        internal static string ERRO_TIPO_INVALIDO {
            get {
                return ResourceManager.GetString("ERRO_TIPO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O tipo não é herdado de IModulo.
        /// </summary>
        internal static string ERRO_TIPO_NAO_HERDADO {
            get {
                return ResourceManager.GetString("ERRO_TIPO_NAO_HERDADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O tipo não esta marcado como modulo.
        /// </summary>
        internal static string ERRO_TIPO_NAO_MARCADO {
            get {
                return ResourceManager.GetString("ERRO_TIPO_NAO_MARCADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O tipo não pode ser void.
        /// </summary>
        internal static string ERRO_TIPO_VOID {
            get {
                return ResourceManager.GetString("ERRO_TIPO_VOID", resourceCulture);
            }
        }
    }
}
